###

POST http://localhost:3000/register
Content-Type: application/json
{
    "username": "manohar_star_95",
    "name": "Manohar Kumar",
    "password": "Tyson@95",
    "gender": "Male",
    "location": "Kozhikode"
}

###

POST http://localhost:3000/login
Content-Type: application/json 
{
    "username": "manohar_star_95",
    "password": "Tyson@93"
}


###

PUT http://localhost:3000/change-password 
Content-Type: application/json 
{
  "username": "manohar_star_95",
  "oldPassword": "Tyson@22",
  "newPassword": "Tyson@93"
}